### ISSUE TITLE
New Release Please

### ISSUE THREAD

**Issue by qec-pconner** [filmil/bazel-bats#7]
First off, thank you for creating this repo.

The last release 0.29.1 was released on Sep 26, 2019 . Since then there have been a number of great additions; namely, usage of `http_archive()` over `new_git_repository()` (which is more secure).

This issue is to simply request a newly published release that includes these changes (and others).

Thanks!

P.S. The WORKSPACE sample in the README is not consistent. It targets 0.29.1 (latest release), which does not support the (commented) `sha256` parameter. Once a new release were to be published, and the README references it, it would work fine. Thanks again.

**Comment by filmil** [comment]
Oh! 

Well, I guess this is a good problem to have.

Two reasons why I didn't do anything about this for so long:
1. I didn't know that anyone cared either way. I guess someone does.
2. I moved away from the work I was doing at the time, so it was no longer that pressing to get things going.

I'll see to find the time to make the changes. If you want to have it sooner, feel free to send PRs.

**Comment by qec-pconner** [comment]
Hey, thanks for the super fast reply!

The only thing that I'm looking for is a new release (new tag) so that `HEAD` can be retrieved via tar.gz (with sha256) on github.
 I'm not sure what your version numbering system is, but I am just looking for a tag of `HEAD`.

**Comment by filmil** [comment]
FYI there's a new tag now, but do be patient for the touch-ups of other issues you noticed.

**Comment by qec-pconner** [comment]
Hey, I have some local changes to update the README and add some features. Will likely send to you tomorrow. Thanks again for putting this project together! :)

**Comment by filmil** [comment]
Sure, bring it on. Glad that this is useful to you.

**Comment by qec-pconner** [comment]
Sent out small PRs for each piece (hopefully easier for review).

* https://github.com/filmil/bazel-bats/pull/8 updates the README to use the latest tag (as mentioned at the start of this bug).
* https://github.com/filmil/bazel-bats/pull/9 updates bats-core version to 1.7.0 (current latest).
* https://github.com/filmil/bazel-bats/pull/10 adds bats-assert and bats-support as (optional) `http_archive()`s added in `bazel_bats_dependencies()`.
* https://github.com/filmil/bazel-bats/pull/11 updates the `bats_test()` rule definition to properly copy over bats-assert (and bats-support) files to be available for .bats test files.

All of these can be submitted in order. Sorry that the diffs in the later PRs are harder to read, as they contain all the changes in previous PRs. Feel free to review and/or approve. :smile: I'm happy to merge them in as appropriate after approval.

Once those get in, it would be great to get a new tag released with those changes. I'd be happy to update the README one last time to target the new tag.

Thanks again!

**Comment by filmil** [comment]
Thank you for your PRs. Please allow me some time to look through these.

**Comment by filmil** [comment]
Let's make a new release once all of the now outstanding PRs are merged.

**Comment by vpanta** [comment]
Just to give some public feedback: I'd love to see this get updated as well!
#subscribe

**Comment by filmil** [comment]
I disabled the problem tests for now, so I think current PRs should be unblocked.

**Comment by vpanta** [comment]
So are we just waiting on @qec-pconner to take some action? What's next to get this moving?

**Comment by qec-pconner** [comment]
https://github.com/filmil/bazel-bats/pull/9 should be good to merge.

I've also put out https://github.com/filmil/bazel-bats/pull/16, which is more fixes for parallel tests.

**Comment by filmil** [comment]
Alright, I'll try to get everything done tonight.

**Comment by qec-pconner** [comment]
Thanks for merging https://github.com/filmil/bazel-bats/pull/9.

https://github.com/filmil/bazel-bats/pull/10 is now good to go.

**Comment by filmil** [comment]
https://github.com/filmil/bazel-bats/releases/tag/v0.31.0 is now available. 

Will need to specify the SHA256 of the release, though, I don't think it's possible to do in the same commit. :)

**Comment by vpanta** [comment]
Thank y'all for getting this settled, we really appreciate it!
